### ISSUE TITLE
become:yes for install tasks

### ISSUE THREAD

**Issue by asmodehn** [spk/ansible-syncthing-debian#2]
Shouldn't the task in install.yml have become:yes ?
I am thinking these install tasks always require root... but not the tasks in configure.yml.

That would avoid running the whole role with become:yes.

However, it might be considered bad to have become: permission down into the role, less clear than if they were in the playbook itself ?

I m curious what is your opinion on this...

**Comment by spk** [comment]
`install.yml` should not have `become: yes` its on your playbook that you can override that.
